# /etc/ddns-forward.ini
# Configuration for ddns-forward port forwarding daemon.
# Supported proto values: tcp, udp, or both.
[forward_1]
remote_target = mytcp.example.com
remote_port = 7000
local_target = 1.2.3.4
local_port = 7000
proto = tcp

[forward_2]
remote_target = myudp.example.com
remote_port = 2096
local_target = 1.2.3.4
local_port = 2096
proto = udp
